# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'FCGraze' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FCGraze

    pod 'AFNetworking' , '~> 3.1.0'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYImage'
    pod 'YYModel'
    pod 'YYWebImage'
    pod 'YYText'
    pod 'YYCategories'
    pod 'DZNEmptyDataSet'
    pod 'CYLTabBarController', '~> 1.17.4'
    pod 'IQKeyboardManager'
    pod 'WMPageController'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'FDFullscreenPopGesture'
    pod 'ReactiveObjC'

end

